ARDMK_DIR = ../Arduino-Makefile/arduino-mk
ARDMK_PATH = ../Arduino-Makefile/bin

ARDUINO_DIR = /Applications/Arduino.app/Contents/Resources/Java
AVR_TOOLS_DIR = /usr/local

BOARD_TAG = atmega328
#BOARD_TAG = uno
ARDUINO_PORT = /dev/tty.usb*

include $(ARDMK_DIR)/Arduino.mk
